# Generated by Django 4.1.5 on 2023-03-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_name", models.CharField(max_length=50)),
                ("device_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_name", models.CharField(max_length=50)),
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rep_app.device"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("com_name", models.CharField(max_length=50)),
                ("com_id", models.IntegerField(primary_key=True, serialize=False)),
                ("dev_status", models.CharField(max_length=15)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rep_app.user"
                    ),
                ),
            ],
        ),
    ]
