# Generated by Django 4.1.5 on 2023-03-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rep_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="user_id", new_name="user_id_f",
        ),
        migrations.RenameField(
            model_name="user", old_name="device_id", new_name="device_id_f",
        ),
    ]
